version: "3.9"
services:
  nuclei:
    image: "projectdiscovery/nuclei:latest"
    volumes:
      - "./nuclei-templates/:/app/nuclei-templates"
      - "./scan.sh:/scan.sh"
      - "./urls.txt:/urls.txt"
    network_mode: host
    entrypoint: "/scan.sh"
